modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "${archives_name}"
version = "${version}"
displayName = "${display_name}"
authors = "NecroSo1"
description = "${description}"

[[dependencies.cobblemonraiddens]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonraiddens]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonraiddens]]
modId = "cobblemon"
mandatory = true
versionRange = "[${cobblemon_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemonraiddens]]
modId = "geckolib"
mandatory = true
versionRange = "[${geckolib_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemonraiddens]]
modId = "mega_showdown"
mandatory = false
type = "optional"
versionRange = "[1.0+1.7+1.21.1,)"

[[dependencies.cobblemonraiddens]]
modId = "cobbledollars"
mandatory = false
type = "optional"
versionRange = "[2.0.0,)"

[[dependencies.cobblemonraiddens]]
modId = "cobblemonsizevariation"
mandatory = false
type = "optional"
versionRange = "[1.4.0,)"

[[dependencies.cobblemonraiddens]]
modId = "rctapi"
mandatory = false
type = "optional"
versionRange = "[0.14.0,)"

[[dependencies.cobblemonraiddens]]
modId = "wthit"
type = "discouraged"

[[mixins]]
config = "${archives_name}-common.mixins.json"

[[mixins]]
config = "${archives_name}-neoforge.mixins.json"